name: MassSayReborn
version: ${project.version}
main: dev.demeng.msr.MassSayReborn
api-version: 1.13
author: Demeng
description: Make all your players say whatever you want!
website: https://demeng.dev/
